
server:
  port: 8080

spring:
  application:
    name: service-registry

eureka:
  instance:
    preferIpAddress: true
    # hostname: beeja-api-service-registry-service
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}