server:
  port: 8000
  reactive:
    session:
      timeout: 2880m

spring:
  session:
    timeout: 2880m
  application:
    name: api-gateway
  data.mongodb:
    uri: ${MONGO_DB_URI}
    database: ${MONGO_DATABASE_NAME}

  cloud:
    gateway:
      globalcors:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          - AddResponseHeader=Access-Control-Allow-Origin, *
        cors-configurations:
          '[/**]':
            allowed-origins:
              - ${FRONTEND_URL}
            allowedMethods:
              - "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: ACCOUNTS-SERVICE
          uri: lb://ACCOUNTS-SERVICE
          predicates:
            - Path= /accounts/**
          filters:
            - CustomTokenRelay=true

        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path= /employees/**
          filters:
            - CustomTokenRelay=true
        - id: EXPENSE-SERVICE
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path= /expenses/**
          filters:
            - CustomTokenRelay=true
        - id: FINANCE-SERVICE
          uri: lb://FINANCE-SERVICE
          predicates:
            - Path= /finance/**
          filters:
            - CustomTokenRelay=true

  mvc:
    favicon:
      location: classpath:/resources/static/favicon.ico

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

auth.cors.allowed-origins:
  frontEndUrl: ${FRONTEND_URL}

management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

resource-server-urls:
  accounts-service: ${ACCOUNTS_SERVICE_BASE_URL}
  employee-service: ${EMPLOYEE_SERVICE_BASE_URL}
  file-service: ${FILE_SERVICE_BASE_URL}
  expense-service: ${EXPENSE_SERVICE_BASE_URL}
  finance-service: ${FINANCE_SERVICE_BASE_URL}

jwt:
  secret: ${JWT_SECRET_KEY}