server:
  servlet:
    context-path: /recruitments
  port: 8095
spring:
  application:
    name: recruitment-service
  data:
    mongodb:
      uri: mongodb://root:password@beeja-db-1:27017/?replicaSet=rs0&directConnection=true
      database: accounts_sbox


eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://beeja-service-registry:8761/eureka

# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openApi.yaml

client-urls:
  accountsService: http://beeja-accounts:8080/accounts
  fileService: http://beeja-file-management:8090/files


jwt:
  secret: zj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXw
