package com.beeja.api.financemanagementservice.enums;

public enum ErrorType {
  API_ERROR,
  SERVICE_ERROR,
  AUTHENTICATION_ERROR,
  AUTHORIZATION_ERROR,
  CONFLICT_ERROR,
  VALIDATION_ERROR,
  RESOURCE_NOT_FOUND_ERROR,
  PERMISSION_NOT_ENABLED_ERROR,
  RESOURCE_EXISTS_ERROR,
  PERMISSION_NOT_ENABLED,
  NUll_VALUE_ERROR,
  MEMORY_ERROR,
  DB_ERROR,
  ASYNC_ERROR;
}
