server:
  servlet:
    context-path: /expenses
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  port: 8091
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: expense-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/?replicaSet=rs0&directConnection=true
      database: expenses_sbox
#      uri: mongodb+srv://dev:aNMEMb7EL2tjJWMN@beeja-all-custer.fmlhx.mongodb.net/?retryWrites=true&w=majority
#      database: expenses_dev

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

authentication:
  clientId: 650017941051-2mispo5ojqjlra0ervqt2gvsvq8j7223.apps.googleusercontent.com
  tokenUri: https://www.googleapis.com/oauth2/v3/tokeninfo

client-urls:
  accountsService: http://localhost:8080/accounts
  fileService: http://localhost:8090/files

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openApi.yaml

file-format:
  allowedTypes:
    - application/pdf
    - image/png
    - image/jpeg

jwt:
  secret: zj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXw