export const EMPLOYEE_MODULE = {
  READ_EMPLOYEE: 'REMP',
  CREATE_EMPLOYEE: 'CEMP',
  UPDATE_EMPLOYEE: 'UEMP',
  CHANGE_STATUS: 'IEM',
  UPDATE_ROLES_AND_PERMISSIONS: 'URAP',
  UPDATE_ALL_EMPLOYEES: 'UALEMP',

  READ_COMPLETE_EMPLOYEE_DETAILS: 'RCEMP',
  READ_ENTIRE_DOCUMENTS: 'RALDOC',
  GET_ALL_EMPLOYEES: 'GALEMP',
};

export const DOCUMENT_MODULE = {
  CREATE_DOCUMENT: 'CDM',
  READ_DOCUMENT: 'RDM',
  UPDATE_DOCUMENT: 'UDM',
  DELETE_DOCUMENT: 'DDM',
  CREATE_ENTIRE_DOCUMENTS: 'CALDOC',
  DELETE_ENTIRE_DOCUMENTS: 'DALDOC',
  READ_ENTIRE_DOCUMENTS: 'RALDOC',
};

export const HEALTH_INSURANCE_MODULE = {
  CREATE_HEALTH_INSURANCE: 'CHIN',
  READ_HEALTH_INSURANCE: 'RHIN',
  UPDATE_HEALTH_INSURANCE: 'UHIN',
  DELETE_HEALTH_INSURANCE: 'DHIN',
};

export const INVENTORY_MODULE = {
  CREATE_DEVICE: 'CDEV',
  READ_DEVICE: 'RDEV',
  UPDATE_DEVICE: 'UDEV',
  DELETE_DEVICE: 'DDEV',
};

export const LOAN_MODULE = {
  READ_LOAN: 'RLON',
  CREATE_LOAN: 'CLON',
  UPDATE_LOAN: 'ULON',
  DELETE: 'DLON',
  STATUS_CHANGE: 'SCLON',
  GET_ALL_LOANS: 'GALON',
};

export const BULK_PAYSLIP_MODULE = {
  CREATE_BULK_PAYSLIP: 'CBPS',
};

export const EXPENSE_MODULE = {
  CREATE_EXPENSE: 'CEX',
  UPDATE_EXPENSE: 'UEX',
  READ_EXPENSE: 'REX',
  DELETE_EXPENSE: 'DEX',
};

export const ORGANIZATION_MODULE = {
  UPDATE_ORGANIZATION: 'UORG',
  READ_ORGANIZATIONS: 'RORG',
};

export const FEATURE_TOGGLES_MODULE = {
  UPDATE_FEATURE: 'UALFTG',
};

export const PERMISSION_MODULE = {
  CREATE_ROLES_OF_ORGANIZATIONS: 'CRORG',
  DELETE_ROLES_OF_ORGANIZATIONS: 'DRORG',
  UPDATE_ROLES_OF_ORGANIZATIONS: 'URORG',
};

export const KYC_MODULE = {
  UPDATE_KYC: 'UKYC',
  UPDATE_ALL_KYC: 'UALKYC',
  READ_KYC: 'RKYC',
  READ_ALL_KYC: 'RALKYC',
};

export const PROFILE_PIC_MODULE = {
  UPDATE_PROFILE_PHOTO_SELF: 'UPPS',
  UPDATE_PROFILE_PHOTO_ALL: 'UPPA',
};
