export const ROLE_BEEJA_ADMIN = 'ROLE_BEEJA_ADMIN';
export const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';
export const ROLE_EMPLOYEE = 'ROLE_EMPLOYEE';
export const ROLE_HR_ADMIN = 'ROLE_HR_ADMIN';
export const ROLE_HR_ASSOCIATE = 'ROLE_HR_ASSOCIATE';
export const ROLE_ACCOUNT_MANAGER = 'ROLE_ACCOUNT_MANAGER';
