server:
  servlet:
    context-path: /employees
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: employee-service
  data:
    mongodb:
      auto-index-creation: true
      database: ${MONGODB_DB_NAME}
      uri: ${MONGODB_URI}


eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

client-urls:
  accountsService: ${ACCOUNTS_SERVICE_BASE_URL}/accounts
  fileService: ${FILE_SERVICE_BASE_URL}/files

jwt:
  secret: ${JWT_SECRET_KEY}
