server:
  servlet:
    context-path: /employees
  port: 8089
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: employee-service
  data:
    mongodb:
      uri: mongodb://root:password@beeja-db-1:27017/?replicaSet=rs0&directConnection=true
      database: employees_sbox

eureka:
  client:
    serviceUrl:
      defaultZone: http://beeja-service-registry:8761/eureka

# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

client-urls:
  accountsService: http://beeja-accounts:8080/accounts
  fileService: http://beeja-file-management:8090/files


jwt:
  secret: zj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXw