server:
  servlet:
    context-path: /files
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  port: 8090
spring:
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  application:
    name: file-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://root:password@beeja-db-1:27017/?replicaSet=rs0&directConnection=true
      database: files_sbox

beeja:
  fileUploadLocation: /beeja-file-storage

javers:
  mappingStyle: FIELD
  algorithm: SIMPLE
  commitIdGenerator: synchronized_sequence
  prettyPrint: true
  typeSafeValues: false
  initialChanges: true
  terminalChanges: true
  packagesToScan:
  auditableAspectEnabled: true
  springDataAuditableRepositoryAspectEnabled: true
  usePrimitiveDefaults: true
  prettyPrintDateFormats:
    localDateTime: 'dd MMM yyyy, HH:mm:ss'
    zonedDateTime: 'dd MMM yyyy, HH:mm:ssZ'
    localDate: 'dd MMM yyyy'
    localTime: 'HH:mm:ss'
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 5000
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://beeja-service-registry:8761/eureka
client-urls:
  employeeService: http://beeja-employee-management:8089/employees
  accountsService: http://beeja-accounts:8080/accounts

management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openApi.yaml
file-format:
  allowedTypes:
    - application/pdf
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/msword
    - image/png
    - image/jpeg
jwt:
  secret: zj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXwzj1pbrDrd305tzhIhUbCC6TpMaayzG6JlSLsYqOzXw