# name: Accounts - Run JUnit Tests

# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'beeja-services/beeja-accounts/**'


# jobs:
#   junit-tests:
#     # if: contains(github.event.pull_request.changed_files, 'beeja-services/beeja-accounts/src')
#     runs-on: ubuntu-24.04

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v4

#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         distribution: 'temurin'
#         java-version: '17'

#     - name: Install Dependencies
#       working-directory: beeja-services/beeja-accounts
#       run: ./gradlew dependencies

#     - name: Run Tests
#       working-directory: beeja-services/beeja-accounts
#       run: ./gradlew test

#     - name: Upload Test Results
#       if: always()
#       uses: actions/upload-artifact@v3
#       with:
#         name: junit-results
#         path: beeja-services/beeja-accounts/build/test-results/test/
