name: Web  Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'beeja-web/**'
jobs:
  trivy-scan-vuln-type:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref:  './beeja-web'            # Scans project files
          vuln-type: 'library'         # Only dependencies
          format: 'sarif'              # Output format for GitHub Security
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'    # Only critical & high vulnerabilities

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif