name: Accounts Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'beeja-services/beeja-accounts/**'
jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Spotless Apply
      working-directory: beeja-services/beeja-accounts
      run: gradle spotlessApply

    - name: Run Checkstyle
      working-directory: beeja-services/beeja-accounts
      run: gradle checkstyleMain

  junit-tests:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Tests
      working-directory: beeja-services/beeja-accounts
      run: gradle test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-results
        path: build/test-results/test/